FROM node:18-alpine 

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json  package-lock.json* ./

RUN npm ci

COPY . .

ARG VITE_APP_API_BASE_URL
ENV VITE_APP_API_BASE_URL=${VITE_APP_API_BASE_URL}

RUN npm run build

EXPOSE 7000

CMD [ "npm", "run", "dev" ]


