version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_API_BASE_URL: ${VITE_APP_API_BASE_URL}
    ports:
      - "7000:7000"
    environment:
      VITE_APP_API_BASE_URL: ${VITE_APP_API_BASE_URL}
